# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 13:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=255)),
                ('owner_id', models.UUIDField()),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
