# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='euser',
            name='one_c_id',
            field=models.UUIDField(auto_created=True, default='00000000-0000-0000-0000-000000000000'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='день рождения'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='администратор'),
        ),
    ]
