# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0002_auto_20161210_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='euser',
            name='is_admin',
        ),
    ]
