# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0003_remove_euser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='euser',
            name='accounts',
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
