# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0003_auto_20161128_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='euser',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
    ]
