# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0004_auto_20161212_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='owner',
            new_name='euser',
        ),
    ]
