# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import personal_cabinet.models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0004_euser_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euser',
            name='phones',
            field=personal_cabinet.models.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
