# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 11:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0005_auto_20161212_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month_balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='address_str',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='date_closed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='date_open',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 11, 21, 35, 856732, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='account',
            name='fias_address_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ic_owner_id',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
        ),
        migrations.AddField(
            model_name='account',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='account',
            name='euser',
        ),
        migrations.AddField(
            model_name='account',
            name='euser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='month_balance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_cabinet.Account'),
        ),
    ]
