# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-28 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0006_auto_20161128_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Номер телефона'),
        ),
    ]
