# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0007_auto_20161212_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Month_balance',
            new_name='MonthBalance',
        ),
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 11, 24, 8, 952219, tzinfo=utc)),
        ),
    ]
