# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 11:40
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0008_auto_20161212_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthbalance',
            name='credit',
            field=models.FloatField(default=0, verbose_name='Начислено'),
        ),
        migrations.AddField(
            model_name='monthbalance',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 11, 40, 27, 302172, tzinfo=utc), unique_for_month=True, verbose_name='месяц расчета'),
        ),
        migrations.AddField(
            model_name='monthbalance',
            name='debt',
            field=models.FloatField(default=0, verbose_name='Задолжность'),
        ),
        migrations.AddField(
            model_name='monthbalance',
            name='discounts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='monthbalance',
            name='payment',
            field=models.FloatField(default=0, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='monthbalance',
            name='price',
            field=models.FloatField(default=0, verbose_name='суммарная цена услуг с человека'),
        ),
        migrations.AddField(
            model_name='monthbalance',
            name='user_count',
            field=models.IntegerField(default=0, verbose_name='Количество проживающих'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(auto_now=True),
        ),
    ]
