# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0010_auto_20161212_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(auto_now_add=True),
        ),
    ]
