# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0011_auto_20161212_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 12, 4, 14, 374658, tzinfo=utc)),
        ),
    ]
