# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 12:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0012_auto_20161212_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_closed',
            field=models.DateField(help_text='если пустое значение - значит бессрочный', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 12, 6, 48, 954883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='euser',
            field=models.ForeignKey(default=1, help_text='Владелец лицевого счета', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='fias_address_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='номер лицевого счета', max_length=12, primary_key=True, serialize=False),
        ),
    ]
