# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 12:43
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0013_auto_20161212_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 12, 43, 11, 717567, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='monthbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_cabinet.Account', verbose_name='Лицевой счет'),
        ),
        migrations.AlterField(
            model_name='monthbalance',
            name='discounts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='В рублях через запятую. Например: 20,50', null=True, size=None, verbose_name='Скидки'),
        ),
    ]
