# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 12:44
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0014_auto_20161212_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 12, 44, 11, 186184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='monthbalance',
            name='discounts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='В рублях через запятую. Например: 20,50', null=True, size=None, verbose_name='Скидки'),
        ),
    ]
