# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 07:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0015_auto_20161212_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Лицевой счет', 'verbose_name_plural': 'Лицевые счета'},
        ),
        migrations.AlterModelOptions(
            name='monthbalance',
            options={'verbose_name': 'Баланс по месяцам', 'verbose_name_plural': 'Балансы по месяцам'},
        ),
        migrations.AddField(
            model_name='euser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address_str',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_closed',
            field=models.DateField(help_text='если пустое значение - значит бессрочный', null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(default=datetime.datetime(2016, 12, 22, 7, 41, 49, 924885, tzinfo=utc), verbose_name='дата открытия'),
        ),
        migrations.AlterField(
            model_name='account',
            name='euser',
            field=models.ForeignKey(default=1, help_text='Владелец лицевого счета', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fias_address_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Код адреса в системе fias'),
        ),
        migrations.AlterField(
            model_name='account',
            name='ic_owner_id',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000', verbose_name='код пользователя в 1с'),
        ),
        migrations.AlterField(
            model_name='account',
            name='message',
            field=models.TextField(null=True, verbose_name='сообщение пользователю'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='номер лицевого счета', max_length=12, primary_key=True, serialize=False, verbose_name='Лицевой счет'),
        ),
    ]
