# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 11:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0018_auto_20161222_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(default=datetime.datetime(2017, 1, 29, 11, 54, 16, 373858, tzinfo=utc), verbose_name='дата открытия'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='phone',
            field=models.IntegerField(blank=True, max_length=30, verbose_name='Номер телефона'),
        ),
    ]
