# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0019_auto_20170129_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(default=datetime.datetime(2017, 1, 29, 11, 57, 51, 814911, tzinfo=utc), verbose_name='дата открытия'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='phone',
            field=models.IntegerField(blank=True, verbose_name='Номер телефона'),
        ),
    ]
