# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0020_auto_20170129_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='euser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код активации'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(default=datetime.datetime(2017, 1, 29, 14, 41, 2, 857093, tzinfo=utc), verbose_name='дата открытия'),
        ),
    ]
