# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0021_auto_20170129_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(default=datetime.datetime(2017, 1, 31, 5, 20, 42, 994564, tzinfo=utc), verbose_name='дата открытия'),
        ),
        migrations.AlterField(
            model_name='euser',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер телефона'),
        ),
    ]
