# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-02 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0022_auto_20170131_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_open',
            field=models.DateField(verbose_name='дата открытия'),
        ),
    ]
