# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_cabinet', '0023_auto_20170202_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
