# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:54
from __future__ import unicode_literals

from django.db import migrations
import sorl_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic',
            name='img_crop',
            field=sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='1000x1618', verbose_name='Обрезка оригинала'),
        ),
        migrations.AlterField(
            model_name='lic',
            name='img_crop_thumbnail',
            field=sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='263x425', verbose_name='Обрезка миниатюры'),
        ),
    ]
