# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:48
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_auto_20170622_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='euser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Номер телефона'),
        ),
    ]
