# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_auto_20170622_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='account',
            name='cdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='monthbalance',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активное'),
        ),
        migrations.AddField(
            model_name='monthbalance',
            name='cdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
