# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_auto_20170626_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthbalance',
            name='discounts',
        ),
        migrations.AddField(
            model_name='monthbalance',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Скидка'),
        ),
    ]
